version: '3'
services:
  italy-itinerary:
    image: nginx:alpine
    container_name: italy-itinerary
    volumes:
      - ./:/usr/share/nginx/html
    ports:
      - "7000:80"

networks:
  italy-network:
    driver: bridge