version: '3'
services:
  italy-itinerary-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: italy-itinerary-app
    volumes:
      - ./:/app
    ports:
      - "7001:5000"
    environment:
      - FLASK_ENV=development
    command: python /app/app.py

networks:
  italy-network:
    driver: bridge